import { createElement } from 'lwc';
import EXAMPLETEST1 from 'c/eXAMPLETEST1';

describe('c-e-x-a-m-p-l-e-t-e-s-t-1', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-e-x-a-m-p-l-e-t-e-s-t-1', {
            is: EXAMPLETEST1
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});